[project]
name = "bsky-paperbot-sound"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "atproto~=0.0.55",
    "feedparser",
    "pylatexenc",
    "beautifulsoup4"
]
